theme: jekyll-theme-cayman
title: Welcome to AJBN´s page
description: Here I write (a bit) about me and my current projects during my postdoc in Prof. Tiago Guerreiro research group at Lisbon University
